/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlsv;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class StudentManagementPanel extends javax.swing.JPanel {

    private Student sv = new Student();
    private Connection conn = DatabaseConnection.getConnection();
    private PreparedStatement ps;
    private String sql;
    private StudentExcute exc = new StudentExcute();
    private DefaultTableModel tblModel;
    private ResultSet rs;

    /**
     * Creates new form StudentManagementPanel
     */
    public StudentManagementPanel() {
        initComponents();
        initTable();
        loadDatatoTable();
    }

    public void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"MSSV", "Họ và tên", "Sinh nhật", "Địa chỉ", "Giới tính", "Khóa", "Khoa", "Lớp", "Số điện thoại"});
        QLSV_StudentTable.setModel(tblModel);
    }

    public void loadDatatoTable() {
        try {
            List<Student> list = exc.findAll();
            tblModel.setRowCount(0);
            for (Student st : list) {
                tblModel.addRow(new Object[]{
                    st.getMSSV(), st.getName(), st.getDob(), st.getAddress(), st.getGender(), st.getSchoolYear(), st.getDepartment(), st.getLop(), st.getPhoneNumber()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void resetComboBox() {

    }

    public void getStudentInformation() throws ParseException {
        sv.setMSSV(QLSV_MSSV.getText());
        sv.setName(QLSV_Name.getText());
        sv.setDob(new java.sql.Date((new SimpleDateFormat("yyyy-MM-dd").parse(QLSV_DOB.getText())).getTime()));
        sv.setAddress((String) QLSV_Address.getSelectedItem());
        sv.setGender((String) QLSV_Gender.getSelectedItem());
        sv.setSchoolYear((String) QLSV_ComboBoxSchoolYear.getSelectedItem());
        sv.setDepartment((String) QLSV_ComboBoxDepartment.getSelectedItem());
        sv.setLop((String) QLSV_ComboBoxClass.getSelectedItem());
        sv.setPhoneNumber(QLSV_PhoneNumber.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        QLSV_StudentTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        QLSV_ComboBox_Khoa1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        QLSV_MSSV = new javax.swing.JTextField();
        QLSV_Name = new javax.swing.JTextField();
        QLSV_DOB = new javax.swing.JTextField();
        QLSV_PhoneNumber = new javax.swing.JTextField();
        QLSV_ComboBoxSchoolYear = new javax.swing.JComboBox<>();
        QLSV_ComboBoxDepartment = new javax.swing.JComboBox<>();
        QLSV_ComboBoxClass = new javax.swing.JComboBox<>();
        QLSV_AddButton = new javax.swing.JButton();
        QLSV_DeleteButton = new javax.swing.JButton();
        QLSV_EditButton = new javax.swing.JButton();
        QLSV_ShowButton = new javax.swing.JButton();
        QLSV_Address = new javax.swing.JComboBox<>();
        QLSV_Gender = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        QLSV_txtStudentSearch = new javax.swing.JTextField();
        QLSV_btnStudentSeatch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        QLSV_StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        QLSV_StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLSV_StudentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(QLSV_StudentTable);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Sinh Viên");

        jLabel2.setText("MSSV");

        jLabel3.setText("Họ và tên");

        QLSV_ComboBox_Khoa1.setText("Khóa");

        jLabel5.setText("Lớp");

        jLabel6.setText("Khoa");

        jLabel7.setText("Ngày sinh");

        jLabel8.setText("Địa chỉ");

        jLabel9.setText("Giới tính");

        jLabel10.setText("SĐT");

        QLSV_MSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_MSSVActionPerformed(evt);
            }
        });

        QLSV_DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_DOBActionPerformed(evt);
            }
        });

        QLSV_ComboBoxSchoolYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "K12", "K13", "K14", "K15" }));
        QLSV_ComboBoxSchoolYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_ComboBoxSchoolYearActionPerformed(evt);
            }
        });

        QLSV_ComboBoxDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_ComboBoxDepartmentActionPerformed(evt);
            }
        });

        QLSV_ComboBoxClass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                QLSV_ComboBoxClassItemStateChanged(evt);
            }
        });
        QLSV_ComboBoxClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_ComboBoxClassActionPerformed(evt);
            }
        });
        QLSV_ComboBoxClass.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                QLSV_ComboBoxClassPropertyChange(evt);
            }
        });
        QLSV_ComboBoxClass.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                QLSV_ComboBoxClassVetoableChange(evt);
            }
        });

        QLSV_AddButton.setText("Thêm");
        QLSV_AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_AddButtonActionPerformed(evt);
            }
        });

        QLSV_DeleteButton.setText("Xóa");
        QLSV_DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_DeleteButtonActionPerformed(evt);
            }
        });

        QLSV_EditButton.setText("Sửa");
        QLSV_EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_EditButtonActionPerformed(evt);
            }
        });

        QLSV_ShowButton.setText("Hiển thị");
        QLSV_ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_ShowButtonActionPerformed(evt);
            }
        });

        QLSV_Address.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà Rịa-Vũng Tàu", "Bạc Liêu", "Bắc Kạn", "Bắc Giang", "Bắc Ninh", "Bến Tre", "Bình Dương", "Bình Định", "Bình Phước", "Bình Thuận", "Cà Mau", "Cao Bằng", "Cần Thơ (TP)", "Đà Nẵng (TP)", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội (TP)", "Hà Tây", "Hà Tĩnh", "Hải Dương", "Hải Phòng (TP)", "Hòa Bình", "Hồ Chí Minh (TP)", "Hậu Giang", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lào Cai", "Lạng Sơn", "Lâm Đồng", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên - Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái" }));

        QLSV_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        QLSV_btnStudentSeatch.setText("Tìm kiếm");
        QLSV_btnStudentSeatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_btnStudentSeatchActionPerformed(evt);
            }
        });

        jLabel4.setText("Tìm sinh viên theo MSSV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(QLSV_txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(QLSV_btnStudentSeatch)
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLSV_txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLSV_btnStudentSeatch)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(QLSV_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QLSV_MSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QLSV_ComboBox_Khoa1)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QLSV_ComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(QLSV_ComboBoxSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(QLSV_ComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(QLSV_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(QLSV_Address, 0, 180, Short.MAX_VALUE)
                                            .addComponent(QLSV_Gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(22, 22, 22)
                                .addComponent(QLSV_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QLSV_DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QLSV_AddButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QLSV_EditButton)
                                    .addComponent(QLSV_ShowButton)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(QLSV_MSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLSV_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(QLSV_AddButton)
                    .addComponent(QLSV_EditButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QLSV_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(QLSV_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLSV_DeleteButton)
                    .addComponent(QLSV_ShowButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QLSV_ComboBox_Khoa1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(QLSV_ComboBoxSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QLSV_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QLSV_ComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(QLSV_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QLSV_ComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void QLSV_DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QLSV_DOBActionPerformed

    private void QLSV_MSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_MSSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QLSV_MSSVActionPerformed

    private void QLSV_ComboBoxClassPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_QLSV_ComboBoxClassPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_QLSV_ComboBoxClassPropertyChange

    private void QLSV_ComboBoxClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_ComboBoxClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QLSV_ComboBoxClassActionPerformed

    private void QLSV_ComboBoxClassVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_QLSV_ComboBoxClassVetoableChange
        // TODO add your handling code here:

    }//GEN-LAST:event_QLSV_ComboBoxClassVetoableChange

    private void QLSV_ComboBoxClassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_QLSV_ComboBoxClassItemStateChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_QLSV_ComboBoxClassItemStateChanged
    /**/
    private void QLSV_AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_AddButtonActionPerformed
        try {
            StringBuilder sb = new StringBuilder();
            getStudentInformation();
            if (sv.getMSSV().equals("") || sv.getName().equals("") || ((String) QLSV_DOB.getText()).equals("")
                    || sv.getAddress().equals("") || sv.getGender().equals("") || sv.getSchoolYear().equals("")
                    || sv.getDepartment().equals("") || sv.getLop().equals("") || sv.getPhoneNumber().equals("")) {
                sb.append("Vui lòng nhập chỗ còn thiếu");
            } else if (exc.findbyMSSV(sv.getMSSV()) != null) {
                sb.append("Trùng MSSV với sinh viên khác");
            }
            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(null, sb, "Lỗi khi thêm", JOptionPane.ERROR_MESSAGE);
            } else {
                if (exc.addStudent(sv)) {
                    JOptionPane.showMessageDialog(null, "Sinh viên đã được thêm", "Thêm thành công", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Svinh viên không đưược thêm do lỗi", "Lỗi khi thêm", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (ParseException ex) {
            Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_QLSV_AddButtonActionPerformed

    private void QLSV_ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_ShowButtonActionPerformed
        // TODO add your handling code here:
        loadDatatoTable();

    }//GEN-LAST:event_QLSV_ShowButtonActionPerformed

    private void QLSV_EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_EditButtonActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        try {
            if (QLSV_MSSV.getText().equals("") || exc.findbyMSSV((String) QLSV_MSSV.getText()) == null) {
                JOptionPane.showMessageDialog(null, "MSSV đang để trống hoặc không tìm thấy MSSV", "Lỗi khi cập nhật", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    getStudentInformation();
                } catch (ParseException ex) {
                    Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (JOptionPane.showConfirmDialog(null, "Bạn có xác nhận muốn cập nhật sinh viên?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    try {
                        if (exc.updateStudent(sv)) {
                            JOptionPane.showMessageDialog(null, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "Lỗi không cập nhật được", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_QLSV_EditButtonActionPerformed

    private void QLSV_StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLSV_StudentTableMouseClicked
        // TODO add your handling code here:
        int row = QLSV_StudentTable.getSelectedRow();
        if (row >= 0) {
            String MSSV = (String) QLSV_StudentTable.getValueAt(row, 0);
            try {
                sv = exc.findbyMSSV(MSSV);
            } catch (SQLException ex) {
                Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (sv != null) {
                QLSV_MSSV.setText(sv.getMSSV());
                QLSV_Name.setText(sv.getName());
                QLSV_DOB.setText(new SimpleDateFormat("yyyy-MM-dd").format(sv.getDob()));
                QLSV_Address.setSelectedItem((Object) sv.getAddress());
                QLSV_Gender.setSelectedItem((Object) sv.getName());
                QLSV_ComboBoxSchoolYear.setSelectedItem((Object) sv.getSchoolYear());
                QLSV_ComboBoxDepartment.setSelectedItem((Object) sv.getDepartment());
                QLSV_ComboBoxClass.setSelectedItem((Object) sv.getLop());
                QLSV_PhoneNumber.setText(sv.getPhoneNumber());
            }
        }
    }//GEN-LAST:event_QLSV_StudentTableMouseClicked

    private void QLSV_DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_DeleteButtonActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        try {
            if (QLSV_MSSV.getText().equals("") || exc.findbyMSSV((String) QLSV_MSSV.getText()) == null) {
                JOptionPane.showMessageDialog(null, "MSSV đang để trống hoặc không tìm thấy MSSV", "Lỗi khi xóa", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    getStudentInformation();
                } catch (ParseException ex) {
                    Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (JOptionPane.showConfirmDialog(null, "Bạn có xác nhận muốn cập nhật sinh viên?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    try {
                        if (exc.deleteStudent((String) QLSV_MSSV.getText())) {
                            JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "Lỗi không xóa được", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_QLSV_DeleteButtonActionPerformed

    private void QLSV_ComboBoxSchoolYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_ComboBoxSchoolYearActionPerformed
        // TODO add your handling code here:
        Object khoa1 = QLSV_ComboBoxSchoolYear.getSelectedItem();
        ArrayList<String> it = new ArrayList<String>();
        DefaultComboBoxModel model;
        try {
            if (khoa1.equals("K12")) {
                sql = "SELECT code_department FROM k12_department";
            } else if (khoa1.equals("K13")) {
                sql = "SELECT code_department FROM k13_department";
            } else if (khoa1.equals("K14")) {
                sql = "SELECT code_department FROM k14_department";
            } else if (khoa1.equals("K15")) {
                sql = "SELECT code_department FROM k15_department";
            }

            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                it.add(rs.getString(1));
            }
            String[] items = new String[it.size()];
            items = it.toArray(items);
            model = new DefaultComboBoxModel(items);
            QLSV_ComboBoxDepartment.setModel(model);
        } catch (SQLException e) {
            System.out.println("Loi SQL");
        }
    }//GEN-LAST:event_QLSV_ComboBoxSchoolYearActionPerformed

    private void QLSV_ComboBoxDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_ComboBoxDepartmentActionPerformed
        // TODO add your handling code here:
        Object schoolyear = QLSV_ComboBoxSchoolYear.getSelectedItem();
        Object department = QLSV_ComboBoxDepartment.getSelectedItem();
        DefaultComboBoxModel model;
        if (schoolyear.equals("K12")) {
            if (department.equals("CNTT")) {
                String[] items = {"K12 CNTT1", "K12 CNTT2"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("TDH")) {
                String[] items = {"K12 TDH1", "K12 TDH2"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("DUOC")) {
                String[] items = {"K12 DUOC"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            }
        } else if (schoolyear.equals("K13")) {
            if (department.equals("CNTT")) {
                String[] items = {"K13 CNTT1", "K13 CNTT2", "K13 CNTT VJ"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("TDH")) {
                String[] items = {"K13 TDH1", "K13 TDH2"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("DUOC")) {
                String[] items = {"K13 DUOC1", "K13 DUOC2"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("NNA")) {
                String[] items = {"K13 NNA1", "K13 NNA2"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            }
        } else if (schoolyear.equals("K14")) {
            if (department.equals("CNTT")) {
                String[] items = {"K14 CNTT1", "K14 CNTT2", "K14 CNTT3", "K14 CNTT4", "K14 CNTT VJ"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("TDH")) {
                String[] items = {"K14 TDH1", "K14 TDH2", "K14 TDH3"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("DUOC")) {
                String[] items = {"K14 DUOC1", "K14 DUOC2"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("NNA")) {
                String[] items = {"K14 NNA1", "K14 NNA2", "K14 NNA3"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("QTKD")) {
                String[] items = {"K14 QTKD1", "K14 QTKD2"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            }
        } else if (schoolyear.equals("K15")) {
            if (department.equals("CNTT")) {
                String[] items = {"K15 CNTT1", "K15 CNTT2", "K15 CNTT3", "K15 CNTT4", "K15 CNTT5", "K15 CNTT VJ", "K15 KHMT"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("TDH")) {
                String[] items = {"K15 TDH1", "K15 TDH2", "K15 TDH3", "K15 TDH4"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("DUOC")) {
                String[] items = {"K15 DUOC1", "K15 DUOC2", "K15 DUOC3", "K15 DUOC4"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("NNA")) {
                String[] items = {"K15 NNA1", "K15 NNA2", "K15 NNA3", "K15 NNA4"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("QTKD")) {
                String[] items = {"K15 QTKD1", "K15 QTKD2", "K15 QTKD3", "K15 QTKD4"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            } else if (department.equals("CN-OTO")) {
                String[] items = {"K15 CNOTO1", "K15 CNOTO2", "K15 CNOTO3", "K15 CNOTO4"};
                model = new DefaultComboBoxModel(items);
                QLSV_ComboBoxClass.setModel(model);
            }
        }
    }//GEN-LAST:event_QLSV_ComboBoxDepartmentActionPerformed

    private void QLSV_btnStudentSeatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_btnStudentSeatchActionPerformed
        try {
            // TODO add your handling code here:
            String MSSV = (String) QLSV_txtStudentSearch.getText();
            sql = "SELECT * FROM student WHERE MSSV = ?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, MSSV);
            rs = ps.executeQuery();
            if (rs.next()) {
                sv = exc.createStudent(rs);
                tblModel.setRowCount(0);
                tblModel.addRow(new Object[]{
                    sv.getMSSV(), sv.getName(), sv.getDob(), sv.getAddress(), sv.getGender(), sv.getSchoolYear(), sv.getDepartment(), sv.getLop(), sv.getPhoneNumber()
                });
                tblModel.fireTableDataChanged();
            } else JOptionPane.showMessageDialog(null, "Không tìm thấy sinh viên phù hợp", "Lỗi khi tìm kiếm", JOptionPane.ERROR_MESSAGE);
            

        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_QLSV_btnStudentSeatchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QLSV_AddButton;
    private javax.swing.JComboBox<String> QLSV_Address;
    private javax.swing.JComboBox<String> QLSV_ComboBoxClass;
    private javax.swing.JComboBox<String> QLSV_ComboBoxDepartment;
    private javax.swing.JComboBox<String> QLSV_ComboBoxSchoolYear;
    private javax.swing.JLabel QLSV_ComboBox_Khoa1;
    private javax.swing.JTextField QLSV_DOB;
    private javax.swing.JButton QLSV_DeleteButton;
    private javax.swing.JButton QLSV_EditButton;
    private javax.swing.JComboBox<String> QLSV_Gender;
    private javax.swing.JTextField QLSV_MSSV;
    private javax.swing.JTextField QLSV_Name;
    private javax.swing.JTextField QLSV_PhoneNumber;
    private javax.swing.JButton QLSV_ShowButton;
    private javax.swing.JTable QLSV_StudentTable;
    private javax.swing.JButton QLSV_btnStudentSeatch;
    private javax.swing.JTextField QLSV_txtStudentSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
